### ISSUE TITLE
Configure GitHub Task for auto-build

### ISSUE THREAD

**Issue by Lednerb** [Lednerb/bilberry-hugo-theme#202]
The demo page should automatically update when new commits are merged into `master`.

Check all links to the demo page to be adjusted for gh-pages.

**Comment by frigi83** [comment]
I use this `yml` Action for:
- Hugo build (no idea why I need two times to build Hugo correctly, same situation as #208 )
- deploy on my SFTP server
- update the Algolia index

```yml
name: hugo2sftp

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        run: |
          sudo snap install hugo
          rm -rf public/
          hugo
          rm -rf public/
          hugo

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/

      - name: Algolia Search
        run: |
         sudo npm install -g @algolia/cli
         sudo algolia import -s public/algolia.json -a ${{ secrets.ALGOLIA_APPID }} -k ${{ secrets.ALGOLIA_APIKEY }} -n ${{ secrets.ALGOLIA_INDEXNAME}}
```
