### ISSUE TITLE
Giscus comments doesn't work properly

### ISSUE THREAD

**Issue by ohmykreee** [Lednerb/bilberry-hugo-theme#301]
### Version I use
* bilberry-hugo-theme https://github.com/Lednerb/bilberry-hugo-theme/commit/89875278e4403a3702cc1d28e17bf31cbcae83ab
* hugo v0.83.1-5AFE0A57

### Phenomenon
Giscus iframe doesn't show up properly.
![image](https://user-images.githubusercontent.com/76862878/143979196-f8a80b3f-8253-4ea4-8631-2d204314f316.png)
(Text in this picture means: giscus.app refuse to connect.)

Errors in the console:
```
Failed to load resource: the server responded with a status of 404 ()
Refused to frame 'https://giscus.app/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

Part of my `config.toml`:
```toml
# Change to one of your content languages defined at the end.
DefaultContentLanguage = "zh-cn"

[params]
  # Enable / Disable Giscus comments
  giscus             = true
  giscusJsUrl        = "https://giscus.app/client.js"
  giscusRepository   = "ohmykreee/kreee-blog"
  giscusRepositoryId = "MDEwOlJlcG9zaXRvcnkzNzQxMjE4ODE="
  giscusMapping      = "og:title"
  giscusCategory     = "Comments"
  giscusCategoryId   = "DIC_kwDOFkylmc4B_6vB"
  giscusTheme        = "light"
  giscusReactions    = "1"
  giscusEmitMetadata = "0"
  giscusLanguage     = "zh-CN"
  giscusCrossOrigin  = "anonymous"
```

### Possible causes
While I editing `/themes/bilberry-hugo-theme/layouts/partials/giscus.html` for debug purpose, I found that if I changed this:
```
        data-theme="{{ .Site.Params.giscusTheme }}"
        {{ if isset .Site.Params "giscusLanguage" }}
        data-lang="{{ .Site.Params.giscusLanguage }}"
        {{ else }}
        data-lang="{{ .Site.Language.Lang }}"
        {{ end }}
```
into hard-coded this:
```
        data-lang="zh-CN"
```
![image](https://user-images.githubusercontent.com/76862878/143980204-2a164ac2-ba68-4afd-b49d-4ceb0d9cd03a.png)
Problem solved.

Then I edited `/themes/bilberry-hugo-theme/layouts/partials/giscus.html` into this to figure out what value it passed to `data-lang`:
```html
{{ if .Site.Params.giscus }}
    <script src="{{ .Site.Params.giscusJsUrl }}"
        data-repo="{{ .Site.Params.giscusRepository }}"
        data-repo-id="{{ .Site.Params.giscusRepositoryId }}"
        data-category="{{.Site.Params.giscusCategory}}"
        data-category-id="{{ .Site.Params.giscusCategoryId }}"
        data-mapping="{{ .Site.Params.giscusMapping }}"
        data-reactions-enabled="{{ .Site.Params.giscusReactions }}"
        data-emit-metadata="{{ .Site.Params.giscusMetadata }}"
        data-theme="{{ .Site.Params.giscusTheme }}"
        {{ if isset .Site.Params "giscusLanguage" }}
        data-lang="{{ .Site.Params.giscusLanguage }}"
        {{ else }}
        data-lang="{{ .Site.Language.Lang }}"
        {{ end }}
        crossorigin="{{ .Site.Params.giscusCrossOrigin }}"
        async>
</script>
    <div id="giscus"></div>

    <div>
        {{ if isset .Site.Params "giscusLanguage" }}
        {{ .Site.Params.giscusLanguage }}
        {{ else }}
        {{ .Site.Language.Lang }}
        {{ end }}
    </div>
{{ end }}
```
![image](https://user-images.githubusercontent.com/76862878/143980425-f1f2cef2-0d3d-4a8f-8f44-877ca085d5f9.png)
Which shows that `{{ if isset .Site.Params "giscusLanguage" }}` didn't work, ignoring the value I set `giscusLanguage     = "zh-CN"` in config.toml, and use `{{ .Site.Language.Lang }}` instead, where `zh-cn` is invalid to Giscus.

I have no experience in writting hugo theme and I have no idea why `{{ if isset .Site.Params "giscusLanguage" }}` didn't work. But in my opinion **it's no need to write a if condition** since Giscus may not accept value from `{{ .Site.Language.Lang }}`, and Giscus has already given `data-lang` value in their guide. Changing it to this just OK:
```
        data-lang="{{ .Site.Params.giscusLanguage }}"
```
