### ISSUE TITLE
Video container appears duplicated

### ISSUE THREAD

**Issue by bellons91** [Lednerb/bilberry-hugo-theme#621]
Hello. 
When using the `video` template, there's a dark-gray box below the YouTube player.

You can see the issue both in the [homepage](https://www.code4it.dev/):

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/6106586/694f320c-0272-4848-a411-8d03c6ca8e0c)

and in that [specific page](https://www.code4it.dev/video/mvp-buzz-chat/):

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/6106586/b3085c7b-3c81-4dc7-b9d4-41789afe5141)

In that case, the Frontmatter was this:

```yml
title: "[ENG] MVPbuzzChat with Davide Bellone | Christian Buckley"
date: 2024-01-08
draft: false
url: /video/mvp-buzz-chat
categories:
- Video
tags:
 - Career

# Set your video id for
youtube: "LzJaAa_HXKU"         # https://www.youtube.com/watch?v=M7IjJiZUutk -> "M7IjJiZUutk"
vimeo: ""           # https://vimeo.com/239830182 -> "239830182"
prezi: ""           # https://prezi.com/v/5z9shnq7jzxs/what-to-study/ -> "5z9shnq7jzxs"
bilibili: ""        # https://www.bilibili.com/video/BV1Sx411T7QQ -> "BV1Sx411T7QQ"
peertube: ""        # https://vids.tekdmn.me/w/w7WGHX7Lb6mCrbrpF3Xb8V (entire URL)
mp4video: ""        # location of video file (only mp4) 
mp4videoImage: ""   # location of poster image 
```
