### ISSUE TITLE
Error in multilingual site when «en» is not enabled.

### ISSUE THREAD

**Issue by gnaghi** [Lednerb/bilberry-hugo-theme#648]
If you try to enable the multilingual option like this :
`DefaultContentLanguage = "it"`

```
[languages]
  [languages.it]
    weight = 1 
  [languages.de]
    weight = 2

```

You have the following message :

`failed to create config from result: failed to decode "languages": config value "en" for defaultContentLanguage does not match any language definition`

As soon as I replace any language with «en», it works.

**Comment by atsuyaw** [comment]
One of existing languages in your site should be set in config file like:

https://github.com/Lednerb/bilberry-hugo-theme/blob/837f875c84795a1b16cd21534df0a8a6cd3eae05/v4/exampleSite/hugo.toml#L16

In your case, only `it` or `de` may be available.

**Comment by atsuyaw** [comment]
One of existing languages in your site should be set in config file like:

https://github.com/Lednerb/bilberry-hugo-theme/blob/837f875c84795a1b16cd21534df0a8a6cd3eae05/v4/exampleSite/hugo.toml#L16

In your case, only `it` or `de` may be available.

**Comment by igor-baiborodine** [comment]
@gnaghi, try the following config:

```toml
defaultContentLanguage = "it"
[languages]
  [languages.it]
    languageCode = "it"
    weight = 1 
  [languages.de]
    weight = 2
```
